version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: 'yarn install'
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run:
          name: 'Run Tests'
          command: 'yarn test'
  deploy:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/repo
    steps:
      - run:
          name: 'Build Project'
          command: 'yarn build'
      - run:
          name: 'Deploy to Firebase Hosting'
          command: './node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
